"""create cached_resources table

Revision ID: 0ee1179b8806
Revises: 
Create Date: 2026-07-16 10:36:50.525422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee1179b8806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_resources_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_resources_key'))

    op.drop_table('cached_resources')
    # ### end Alembic commands ###
