"""initial crafting schema

Revision ID: 573cab01c2fc
Revises: 
Create Date: 2026-07-16 11:59:18.859214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573cab01c2fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('ilvl', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('acquisition_type', sa.String(length=20), nullable=False),
    sa.Column('vendor_price', sa.Integer(), nullable=True),
    sa.Column('gathering_node_ids', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_game_id'), ['game_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider_identity')
    )
    op.create_table('crafting_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crafting_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crafting_lists_user_id'), ['user_id'], unique=False)

    op.create_table('item_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_components_component_item_id'), ['component_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_components_parent_item_id'), ['parent_item_id'], unique=False)

    op.create_table('crafting_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['crafting_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crafting_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crafting_list_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crafting_list_items_list_id'), ['list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crafting_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crafting_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_crafting_list_items_item_id'))

    op.drop_table('crafting_list_items')
    with op.batch_alter_table('item_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_components_parent_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_components_component_item_id'))

    op.drop_table('item_components')
    with op.batch_alter_table('crafting_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crafting_lists_user_id'))

    op.drop_table('crafting_lists')
    op.drop_table('users')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_game_id'))

    op.drop_table('items')
    # ### end Alembic commands ###
